# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19f24b22837a69b819a74e55b9cb92f6c20c2342d8367b80ae8bb2f38a32597e27aef494fdcda1fded88792fc0f2faa6e85a67f5aa46f5a0423a7af87a502b5

test:
  secret_key_base: c12dfc5ecb7082cd3b8810be165408d1223e6eb3b9973032176bbe1f8f902f5671bf8e98abca62a594a4c141648d8fade98ff2c90295087aaf9fabc395abdeda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
